### ISSUE TITLE
Asset "C:/Program" does not exist

### ISSUE THREAD

**Issue by EG6-dev** [SamVanheer/HL_Tools#244]
I am unaware if this is an issue with Jack (the level editor) or the viewer itself, so just close this if it's not relevant.

when trying to view a model through the jack editor, the warning "Asset "C:/Program" does not exist" is displayed, and then doesn't load the model. the program itself seems to work, but won't load anything from the editor. was wondering if anyone knows what this is about.

**Comment by SamVanheer** [comment]
I've debugged this; JACK is passing the filename without quotes so the filename is split into separate arguments whenever there is whitespace.

You should report this to the JACK developers. The JACK website has more information about how to report bugs: https://jack.hlfx.ru/en/support.html

But do note that fixes will only be made available to the Steam version. The Steam version may already be fixed, i don't have it so i can't test it.

There isn't much i can do about this problem in this program. It looks like i can detect when this problem occurs (but not with 100% accuracy) so i can try to reconstruct the filename. In simple cases it'll fix the problem, but some cases like filenames split in a way to cause a chunk to start with `-` will probably still fail.

**Comment by SamVanheer** [comment]
I'm told that the Steam version handles this correctly, so you'll have to get that version if you want this to be fixed in JACK.

**Comment by SamVanheer** [comment]
I've added a workaround that will attempt to reform the original filename if it's passed without quotes. It handles the common case of a filename split because of whitespace, but only if there is a single space.

You can test this with the current dev build by downloading the artifact from the Github Actions runs: https://github.com/SamVanheer/HL_Tools/actions/runs/3641509984

Note that you'll need to install the latest VC++ x86 redistributable first: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

These are dev builds so they can be buggy. This build has work-in-progress changes so some things don't work as expected. As long as it loads the model as expected i'd consider this issue resolved.
