### ISSUE TITLE
Create HLMV For Android

### ISSUE THREAD

**Issue by Neeekoo-Chan** [SamVanheer/HL_Tools#61]
Can You Create HLMV Tools For Android User

**Comment by SamVanheer** [comment]
I'll see what i can do. An Android port has a lot of requirements so i don't expect to be able to even try for a while.

**Comment by Neeekoo-Chan** [comment]
Thank you thank you 😁

**Comment by Solokiller** [comment]
I will look into this at some point after HLMV 3 is done.

**Comment by CS-PRO1** [comment]
So HLMV 3 aka HLAM is out for a while now. When will this app start development?

**Comment by SamVanheer** [comment]
There are some features that need to be implemented before an Android version can be made.

Android uses the embedded version of OpenGL (OpenGL ES) which has a number of differences with desktop OpenGL. This is the biggest blocker for the Android version since it requires changes to be made to the graphics code.

This article explains some of the issues involving OpenGL usage: https://www.qt.io/blog/2015/09/09/cross-platform-opengl-es-3-apps-with-qt-5-6

HLAM currently uses GLEW to access OpenGL APIs, which is designed for use with desktop OpenGL only.

HLAM 2.0.0 is going to overhaul the graphics code to use Qt's OpenGL API which picks the right OpenGL API depending on your system. In your case Qt will default to ANGLE since the desktop OpenGL version doesn't support all required features (framebuffers are used by Qt internally, but it will handle missing support gracefully), which is why i had to force it to desktop OpenGL.

HLAM currently has one feature that will crash on systems that don't have OpenGL 3 support or newer, which is mipmap generation. OpenGL ES 2 implements this feature, as does ANGLE.

Qt also supports Android, so it might be possible to port HLAM directly to Android using the same codebase.

This requires compiling the program with Clang so before an Android build can be made the codebase has to successfully compile on Linux, where both GCC and Clang are fully supported. This allows GCC and Clang based builds to be tested without having to worry about Android-specific problems.

If GCC works then Clang will most likely work as well.

Once these issues are resolved i can look into making an Android build. I can then see what else needs to be done to make it work (e.g. APIs that need replacing or abstracting out, whether a separate UI needs to be made, stuff like that).

These issues track progress on parts of the requirements:
#10 (functioning makefiles on Linux, should already work but hasn't been tested recently)
#127 (Linux version, covers GCC compilation by nature)
#148 (Will be fixed when the Qt OpenGL API is used everywhere since it allows the use of ANGLE to do OpenGL rendering)
#207 (Will be fixed when the Qt OpenGL API is used everywhere since ANGLE implements this API)

Some other issues will probably affect the Android version as well:
#116 (reduces memory usage by eliminating multiple instances of the UI)
#188 (reduces memory usage)
#196 (reduces memory usage)
#214 (will probably always be turned on on Android for performance reasons)

It'll take a while to get through all of this stuff, so i wouldn't expect an Android version before 2022. Even if i can get a build to work the user interface will probably be limited since it might not fit on a mobile sized screen.

**Comment by Junior-Michael** [comment]
Plz when

**Comment by SamVanheer** [comment]
I've investigated this to see what it would take. Unfortunately there is too much work required and too many problems to justify the work, so i've decided to cancel this.

See this thread for more information: https://twhl.info/thread/view/20070?page=1#post-346730
